version: '3.2'
services:
  db:
   image: mariadb:10.3
   env_file:
     - ./.env
   volumes:
     - type: bind
       source: ./db-data
       target: /var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db 

  dadi:
    build:
      context: .
      dockerfile: Dockerfile-Apache
    image: dadi:apache2
    volumes:
      - type: bind
        source: ./apache/000-default.conf
        target: /etc/apache2/sites-available/000-default.conf
      - type: bind
        source: ./apache/ports.conf
        target: /etc/apache2/ports.conf
      - type: bind
        source: ./www-data/images
        target: /var/www/html/webroot/inc/images
    env_file:
      - ./.env
    ports:
      - 80:8080
    depends_on:
      - db