version: '3.2'
services:
  db:
   image: mariadb:10.3
   env_file:
     - ./.env
   volumes:
     - type: bind
       source: ./db-data
       target: /var/lib/mysql

  adminer:
    image: adminer
    restart: always
    environment:
      - VIRTUAL_HOST=adminer.localhost
      - VIRTUAL_PORT=8080
    depends_on:
      - db

  nginx:
    image: nginx:1.15-alpine
    read_only: true
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=dadi.localhost
      - VIRTUAL_PORT=8080
    volumes:
      - type: volume
        read_only: true
        source: html-data
        target: /var/www/html
        volume:
          nocopy: true
      - type: bind
        source: ./www-data/upload/
        target: /var/www/html/webroot/inc/items/
        volume:
          nocopy: true
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: nginx
        target: /var/cache/nginx
      - type: volume
        source: nginx
        target: /var/run
    depends_on:
      - dadi

  dadi:
    build: .
    image: dadi:fpm
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: html-data
        target: /var/www/html
      - type: bind
        source: ./www-data/upload/
        target: /var/www/html/webroot/inc/items/
        volume:
          nocopy: true
    depends_on:
      - db

  hackmd:
    image: hackmdio/hackmd:1.3-alpine 
    environment:
      - HMD_DB_URL=mysql://hackmd:hackmdpass@db:3306/hackmd
      - VIRTUAL_HOST=hackmd.localhost
      - VIRTUAL_PORT=3000
      - CMD_SESSION_SECRET=R4ND0M$T71N5
      - CMD_DOMAIN=hackmd.localhost
    depends_on:
      - db

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  html-data:
  nginx: