version: '3.2'
services:
  db:
   image: mariadb:10.3
   env_file:
     - ./.env
   volumes:
     - type: bind
       source: ./db-data
       target: /var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db 
  nginx:
    image: nginx:1.15-alpine
    read_only: true
    ports:
    - 80:8080
    environment:
    - NGINX_PORT=80
    volumes:
      - type: volume
        read_only: true
        source: assets
        target: /var/www/html
        volume:
          nocopy: true
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
      - type: volume
        source: nginx
        target: /var/cache/nginx
      - type: volume
        source: nginx
        target: /var/run
    depends_on:
      - dadi
  dadi:
    build: .
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: assets
        target: /var/www/html
    depends_on:
      - db

volumes:
  assets:
  nginx: