version: '3.2'
services:
  db:
   image: mariadb:10.3
   environment:
    - MYSQL_ROOT_PASSWORD=example
    - MYSQL_USER=dadi
    - MYSQL_PASSWORD=dadi
    - MYSQL_DATABASE=dadi
   volumes:
     - type: bind
       source: ./db-data
       target: /var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db 
  nginx:
    image: nginx:1.15-alpine
    ports:
    - 80:80
    environment:
    - NGINX_PORT=80
    volumes:
      - type: volume
        source: assets
        target: /var/www/html
        volume:
          nocopy: true
      - type: bind
        source: ./nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - dadi
  dadi:
    build: .
    volumes:
    - assets:/var/www/html
    depends_on:
      - db

volumes:
  assets:
