{block name="skills-list"}
    <div class="skills-list">
        <div class="skills-list__title">Skills</div>
        <table class="skills-list__table">
          <tr>
            <td>Acrobatics</td>
            <td>{$skills.modAcrobatics}</td>
            <td>{$skills.bonusAcrobatics}</td>
          </tr>
          <tr>
            <td>Animal Handling</td>
            <td>{$skills.modAnimalHandling}</td>
            <td>{$skills.bonusAnimalHandling}</td>
          </tr>
          <tr>
            <td>Arcana</td>
            <td>{$skills.modArcana}</td>
            <td>{$skills.bonusArcana}</td>
          </tr>
          <tr>
            <td>Athletics</td>
            <td>{$skills.modAthletics}</td>
            <td>{$skills.bonusAthletics}</td>
          </tr>
          <tr>
            <td>Athletics <i class="fa fa-star"></i></td>
            <td>{$skills.modAthletics}</td>
            <td>{$skills.bonusAthletics}</td>
          </tr>
          <tr>
            <td>Aeception</td>
            <td>{$skills.modAeception}</td>
            <td>{$skills.bonusAeception}</td>
          </tr>
          <tr>
            <td>History</td>
            <td>{$skills.modHistory}</td>
            <td>{$skills.bonusHistory}</td>
          </tr>
          <tr>
            <td>Insight <i class="fa fa-star"></td>
            <td>{$skills.modInsight}</td>
            <td>{$skills.bonusInsight}</td>
          </tr>
          <tr>
            <td>Intimidation</td>
            <td>{$skills.modIntimidation}</td>
            <td>{$skills.bonusIntimidation}</td>
          </tr>
          <tr>
            <td>Investigation</td>
            <td>{$skills.modInvestigation}</td>
            <td>{$skills.bonusInvestigation}</td>
          </tr>
          <tr>
            <td>Medicine</td>
            <td>{$skills.modMedicine}</td>
            <td>{$skills.bonusMedicine}</td>
          </tr>
          <tr>
            <td>Nature</td>
            <td>{$skills.modNature}</td>
            <td>{$skills.bonusNature}</td>
          </tr>
          <tr>
            <td>Perception</td>
            <td>{$skills.modPerception}</td>
            <td>{$skills.bonusPerception}</td>
          </tr>
          <tr>
            <td>Performance</td>
            <td>{$skills.modPerformance}</td>
            <td>{$skills.bonusPerformance}</td>
          </tr>
          <tr>
            <td>Persuasion</td>
            <td>{$skills.modPersuasion}</td>
            <td>{$skills.bonusPersuasion}</td>
          </tr>
          <tr>
            <td>Religion</td>
            <td>{$skills.modReligion}</td>
            <td>{$skills.bonusReligion}</td>
          </tr>
          <tr>
            <td>Sleight of Hand</td>
            <td>{$skills.modSleightOfHand}</td>
            <td>{$skills.bonusSleightOfHand}</td>
          </tr>
          <tr>
            <td>Stealth</td>
            <td>{$skills.modStealth}</td>
            <td>{$skills.bonusStealth}</td>
          </tr>
          <tr>
            <td>Survival</td>
            <td>{$skills.modSurvival}</td>
            <td>{$skills.bonusSurvival}</td>
          </tr>
        </table>
    </div>
{/block}
